---
abstract: 'Convert between compass point names, abbreviations and values'
author:
  - 'Simon Bertrang <janus@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compass-Points
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: https://github.com/sbertrang/compass-points/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/sbertrang/compass-points.git
version: 0.02
